project:
  type: website

website:
  title: "Jake Harmon"
  site-url: https://jakebharmon.github.io
  description: "Blog of an epidemiologist exploring culture, economics, and data."

format:
  html:
    theme: none
    minimal: true
    css: styles.css
    include-before-body: _navbar.html
    toc: false
    anchor-sections: false


execute:
  freeze: auto
